version: 2.1
jobs:
  build:
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean compile test-compile
  test:
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean test
